name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          cache: true

      - run: flutter clean
      - run: flutter pub get

      - name: Build iOS Simulator
        run: flutter build ios --simulator --release

      - name: Package App
        run: |
          mkdir -p Payload
          cp -R build/ios/iphonesimulator/Runner.app Payload/
          cd Payload
          zip -r ../app.zip .
          cd ..

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: app.zip
